const javaEasyQuestions = [
  {
    question: "What is Java?",
    option1: "An operating system",
    option2: "A programming language",
    option3: " A browser",
    ans: 2,
  },
  {
    question: "What is the purpose of the `main` method in Java?",
    option1: "To print output",
    option2: "To initialize variables",
    option3: " Entry point for program execution",
    ans: 3,
  },
  {
    question: "What is the output of `System.out.println(5 + '10')`?",
    option1: "15",
    option2: 510,
    option3: "550",
    ans: 2,
  },
  {
    question: "Which keyword is used to declare constants in Java`?",
    option1: "`final`",
    option2: "`static`",
    option3: " `const`",
    ans: 1,
  },
  {
    question: "What is the purpose of the `super` keyword in Java??",
    option1: "To call superclass methods",
    option2: "To initialize objects",
    option3: "To create subclasses",
    ans: 1,
  },
  {
    question: "How do you declare an array in Java?",
    option1: "`array myArray;`",
    option2: "`int[] myArray;`",
    option3: " `new Array myArray;`",
    ans: 2,
  },
  {
    question: " What is the correct syntax for a `for` loop in Java?",
    option1: "`for (i=0; i&lt;5; i++) { }`",
    option2: "`for (int i=0; i&lt;5; i++) { }`",
    option3: " `for i=0; i&lt;5; i++ { }`",
    ans: 2,
  },
  {
    question: " Which method is called when an object is created in Java?",
    option1: "`start()`",
    option2: " `run()`",
    option3: " `constructor()`",
    ans: 3,
  },
  {
    question: " What does the `break` statement do in Java?",
    option1: "Terminates the program",
    option2: "Exits the loop or switch statement",
    option3: " Skips the next iteration of the loop",
    ans: 2,
  },
  {
    question: "Which class is used for reading user input in Java?",
    option1: "`InputReader`",
    option2: "`Scanner`",
    option3: "`UserInput`",
    ans: 2,
  },
  {
    question: "WWhat is the purpose of the `static` keyword in Java?*",
    option1: "To create static variables",
    option2: "To make methods accessible without creating an object",
    option3: "To create static classes",
    ans: 2,
  },
  {
    question: "How do you convert a string to an integer in Java?",
    option1: "`Integer.parseInt()`",
    option2: "`String.valueOf()`",
    option3: "`int.parseString()`",
    ans: 1,
  },
  {
    question: "What is the difference between `==` and `.equals()` in Java?",
    option1: "Both compare object references",
    option2: "``==` compares content, `.equals()` compares references",
    option3: "`==` compares references, `.equals()` compares content",
    ans: 3,
  },
  {
    question: "What does the keyword `this` refer to in Java?",
    option1: "Current instance of the class",
    option2: "Superclass",
    option3: "Global object",
    ans: 1,
  },
  {
    question: "What is the purpose of the `interface` keyword in Java?",
    option1: "To declare constants",
    option2: "To declare abstract methods",
    option3: "To create subclasses",
    ans: 2,
  },
];

export default javaEasyQuestions;
